{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.secret }}
  namespace: openldap
spec:
  secretName: {{ .Values.secret }}
  issuerRef:
    name: sample-selfsigned
    kind: ClusterIssuer
  commonName: {{ .Values.env.LDAP_DOMAIN }}
