{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  name: {{ .Values.tls.secret }}
  namespace: openldap
spec:
  secretName: {{ .Values.tls.secret }}
  issuerRef:
    name: sample-selfsigned
    kind: ClusterIssuer
  commonName: {{ .Values.env.LDAP_DOMAIN }}
{{- end }}
