apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: openldap-cert
spec:
  secretName: openldap-tls
  issuerRef:
    name: sample-selfsigned
    kind: ClusterIssuer
  commonName: zdgt.com
  dnsNames:
  - zdgt.com
  - openldap.zdgt.com
